#!/usr/bin/env bash

wallpaper="$HOME/Pictures/Wallpapers/catppuccin/triangle.jpg"

# Show menu options
if [ -z "$@" ]; then
  echo "  Lock"
  echo "󰍃  Logout"
  echo "󰜉  Reboot"
  echo "  Shutdown"
  exit 0
fi

# Match selected option
case "$1" in
  "  Lock")
    exec bash -c "swaymsg input '*' xkb_switch_layout 0 >/dev/null 2>&1; \
      swaylock -f -i \"$wallpaper\" \
      --indicator-radius 80 \
      --indicator-thickness 10 \
      --ring-color ffd75fff"
    ;;
  "󰍃  Logout")
    swaynag \
      -t warning \
      -m "You pressed the exit shortcut. Do you really want to exit Sway? This will end your Wayland session." \
      -B "Yes, exit Sway" "swaymsg exit"
    ;;
  "󰜉  Reboot")
    exec systemctl reboot
    ;;
  "  Shutdown")
    exec systemctl poweroff
    ;;
esac
